### ISSUE TITLE
Q10 missing

### ISSUE THREAD

**Issue by kumasento** [knatten/cppquiz#234] opened 2021-06-06 19:58 UTC
Hi there,

Great website! Really helpful to brush up my C++ knowlegde :)

Just a nit: it seems that Q.10 is not there anymore, would you mind checking that out? What I saw was just 404 not found.

BTW here is the URL I used: https://cppquiz.org/quiz/question/10

**Comment by vsklamm** [comment] 2021-06-06 20:02
Duplicate of #208 and #163

**Closed** 2021-06-06 20:18 UTC
